import { openDB } from "@/utils/db";
import { NextRequest } from "next/server"

const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const baseUrl = process.env.URL!

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const query = searchParams.get('status')
  const sessionId = searchParams.get('session_id')

  const session = await stripe.checkout.sessions.retrieve(sessionId, {
    expand: ['customer', 'invoice.subscription'],
  });

  const db = await openDB()

  try {
    await db.run("UPDATE users SET payment_customer_id = ?, payment_subscription_id = ? where payment_session_id = ?", session.customer.id, session.subscription, sessionId)
    const userData = await db.all('SELECT * FROM users where payment_session_id = ?', sessionId)
    await db.run("UPDATE SubscriptionsUsage SET SubscriptionID = 'PRO_TIER', EndSubscription = DATE(CURRENT_TIMESTAMP, '1 month') WHERE UserID = ?", userData[0].id)
  } catch (error) {
    console.error({ message: "error during save payment details for sessionId", customerId: session.customer.id, subscriptionId: session.subscription, sessionId: sessionId })
  }

  return Response.redirect(baseUrl)
}


// {
//   id: 'cs_test_a1xtDxHWbx9WFyRi1Pwh4XhTQ4Zt8yWZyDpaNkoQ5YAopVPbkiqc9UIfUY',
//   object: 'checkout.session',
//   after_expiration: null,
//   allow_promotion_codes: null,
//   amount_subtotal: 1900,
//   amount_total: 1900,
//   automatic_tax: { enabled: false, liability: null, status: null },
//   billing_address_collection: null,
//   cancel_url: 'http://localhost:3000//api/payment-done?status=cancel',
//   client_reference_id: null,
//   client_secret: null,
//   consent: null,
//   consent_collection: null,
//   created: 1710980424,
//   currency: 'eur',
//   currency_conversion: null,
//   custom_fields: [],
//   custom_text: {
//     after_submit: null,
//     shipping_address: null,
//     submit: null,
//     terms_of_service_acceptance: null
//   },
//   customer: {
//     id: 'cus_Pm7c53JZ5eQ8q0',
//     object: 'customer',
//     address: {
//       city: null,
//       country: 'IT',
//       line1: null,
//       line2: null,
//       postal_code: null,
//       state: null
//     },
//     balance: 0,
//     created: 1710980446,
//     currency: 'eur',
//     default_source: null,
//     delinquent: false,
//     description: null,
//     discount: null,
//     email: 'test@email.com',
//     invoice_prefix: '872AA800',
//     invoice_settings: {
//       custom_fields: null,
//       default_payment_method: null,
//       footer: null,
//       rendering_options: null
//     },
//     livemode: false,
//     metadata: {},
//     name: 'Pinco Panco',
//     phone: null,
//     preferred_locales: [ 'it-IT' ],
//     shipping: null,
//     tax_exempt: 'none',
//     test_clock: null
//   },
//   customer_creation: 'always',
//   customer_details: {
//     address: {
//       city: null,
//       country: 'IT',
//       line1: null,
//       line2: null,
//       postal_code: null,
//       state: null
//     },
//     email: 'test@email.com',
//     name: 'Pinco Panco',
//     phone: null,
//     tax_exempt: 'none',
//     tax_ids: []
//   },
//   customer_email: null,
//   expires_at: 1711066824,
//   invoice: {
//     id: 'in_1OwZNDCkSxKIKX1FcwkalBeS',
//     object: 'invoice',
//     account_country: 'IT',
//     account_name: null,
//     account_tax_ids: null,
//     amount_due: 1900,
//     amount_paid: 1900,
//     amount_remaining: 0,
//     amount_shipping: 0,
//     application: null,
//     application_fee_amount: null,
//     attempt_count: 1,
//     attempted: true,
//     auto_advance: false,
//     automatic_tax: { enabled: false, liability: null, status: null },
//     billing_reason: 'subscription_create',
//     charge: 'ch_3OwZNDCkSxKIKX1F0ZxTXwVn',
//     collection_method: 'charge_automatically',
//     created: 1710980447,
//     currency: 'eur',
//     custom_fields: null,
//     customer: 'cus_Pm7c53JZ5eQ8q0',
//     customer_address: {
//       city: null,
//       country: 'IT',
//       line1: null,
//       line2: null,
//       postal_code: null,
//       state: null
//     },
//     customer_email: 'test@email.com',
//     customer_name: 'Pinco Panco',
//     customer_phone: null,
//     customer_shipping: null,
//     customer_tax_exempt: 'none',
//     customer_tax_ids: [],
//     default_payment_method: null,
//     default_source: null,
//     default_tax_rates: [],
//     description: null,
//     discount: null,
//     discounts: [],
//     due_date: null,
//     effective_at: 1710980447,
//     ending_balance: 0,
//     footer: null,
//     from_invoice: null,
//     hosted_invoice_url: 'https://invoice.stripe.com/i/acct_1Oqv8vCkSxKIKX1F/test_YWNjdF8xT3F2OHZDa1N4S0lLWDFGLF9QbTdjWmJuWlJLR3FSMWdOTExUdk10dGRWUGNyRnM3LDEwMTUyMTI1MQ0200SH53Fbmq?s=ap',
//     invoice_pdf: 'https://pay.stripe.com/invoice/acct_1Oqv8vCkSxKIKX1F/test_YWNjdF8xT3F2OHZDa1N4S0lLWDFGLF9QbTdjWmJuWlJLR3FSMWdOTExUdk10dGRWUGNyRnM3LDEwMTUyMTI1MQ0200SH53Fbmq/pdf?s=ap',
//     issuer: { type: 'self' },
//     last_finalization_error: null,
//     latest_revision: null,
//     lines: {
//       object: 'list',
//       data: [Array],
//       has_more: false,
//       total_count: 1,
//       url: '/v1/invoices/in_1OwZNDCkSxKIKX1FcwkalBeS/lines'
//     },
//     livemode: false,
//     metadata: {},
//     next_payment_attempt: null,
//     number: '02E93569-0015',
//     on_behalf_of: null,
//     paid: true,
//     paid_out_of_band: false,
//     payment_intent: 'pi_3OwZNDCkSxKIKX1F0wgFDHVR',
//     payment_settings: {
//       default_mandate: null,
//       payment_method_options: [Object],
//       payment_method_types: null
//     },
//     period_end: 1710980447,
//     period_start: 1710980447,
//     post_payment_credit_notes_amount: 0,
//     pre_payment_credit_notes_amount: 0,
//     quote: null,
//     receipt_number: null,
//     rendering: null,
//     rendering_options: null,
//     shipping_cost: null,
//     shipping_details: null,
//     starting_balance: 0,
//     statement_descriptor: null,
//     status: 'paid',
//     status_transitions: {
//       finalized_at: 1710980447,
//       marked_uncollectible_at: null,
//       paid_at: 1710980448,
//       voided_at: null
//     },
//     subscription: {
//       id: 'sub_1OwZNDCkSxKIKX1FRs76px8r',
//       object: 'subscription',
//       application: null,
//       application_fee_percent: null,
//       automatic_tax: [Object],
//       billing_cycle_anchor: 1710980447,
//       billing_cycle_anchor_config: null,
//       billing_thresholds: null,
//       cancel_at: null,
//       cancel_at_period_end: false,
//       canceled_at: null,
//       cancellation_details: [Object],
//       collection_method: 'charge_automatically',
//       created: 1710980447,
//       currency: 'eur',
//       current_period_end: 1713658847,
//       current_period_start: 1710980447,
//       customer: 'cus_Pm7c53JZ5eQ8q0',
//       days_until_due: null,
//       default_payment_method: 'pm_1OwZNCCkSxKIKX1Fuo4sKzk2',
//       default_source: null,
//       default_tax_rates: [],
//       description: null,
//       discount: null,
//       ended_at: null,
//       invoice_settings: [Object],
//       items: [Object],
//       latest_invoice: 'in_1OwZNDCkSxKIKX1FcwkalBeS',
//       livemode: false,
//       metadata: {},
//       next_pending_invoice_item_invoice: null,
//       on_behalf_of: null,
//       pause_collection: null,
//       payment_settings: [Object],
//       pending_invoice_item_interval: null,
//       pending_setup_intent: null,
//       pending_update: null,
//       plan: [Object],
//       quantity: 1,
//       schedule: null,
//       start_date: 1710980447,
//       status: 'active',
//       test_clock: null,
//       transfer_data: null,
//       trial_end: null,
//       trial_settings: [Object],
//       trial_start: null
//     },
//     subscription_details: { metadata: {} },
//     subtotal: 1900,
//     subtotal_excluding_tax: 1900,
//     tax: null,
//     test_clock: null,
//     total: 1900,
//     total_discount_amounts: [],
//     total_excluding_tax: 1900,
//     total_tax_amounts: [],
//     transfer_data: null,
//     webhooks_delivered_at: 1710980447
//   },
//   invoice_creation: null,
//   livemode: false,
//   locale: null,
//   metadata: {},
//   mode: 'subscription',
//   payment_intent: null,
//   payment_link: null,
//   payment_method_collection: 'always',
//   payment_method_configuration_details: null,
//   payment_method_options: { card: { request_three_d_secure: 'automatic' } },
//   payment_method_types: [ 'card' ],
//   payment_status: 'paid',
//   phone_number_collection: { enabled: false },
//   recovered_from: null,
//   setup_intent: null,
//   shipping_address_collection: null,
//   shipping_cost: null,
//   shipping_details: null,
//   shipping_options: [],
//   status: 'complete',
//   submit_type: null,
//   subscription: 'sub_1OwZNDCkSxKIKX1FRs76px8r',
//   success_url: 'http://localhost:3000//api/payment-done?status=success&session_id={CHECKOUT_SESSION_ID}',
//   total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
//   ui_mode: 'hosted',
//   url: null
// }